name: Documentations
on:
  push:
    branches:
      - master
jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: cargo doc
        run: |
          cargo install bindgen-cli
          export PATH=$PATH:~/.cargo/bin
          make bindgen
          cargo test
          cargo doc --no-deps

  deploy:
    runs-on: ubuntu-latest
    needs: doc
    steps:
      - name: prepare
        run: |
          git checkout gh-pages
          rm -rf cargo-doc
          mv target/doc cargo-doc
      - name: commit and push
        env:
          TZ: 'Asia/Tokyo'
        run: |
          git add cargo-doc
          git commit -m "${{ steps.date.outputs.date }}"
          git push origin gh-pages
